# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReduceCollateral():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_reduceCollateral(self):
    # Test name: Reduce Collateral
    # Step # | name | target | value
    # 1 | open | /perps-legacy | 
    self.driver.get("https://jup.ag/perps-legacy")
    # 2 | setWindowSize | 1464x946 | 
    self.driver.set_window_size(1464, 946)
    # 3 | click | css=.flex:nth-child(1) > .flex > .flex > .flex > .flex > .h-9:nth-child(2) > .relative | 
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(1) > .flex > .flex > .flex > .flex > .h-9:nth-child(2) > .relative").click()
    # 4 | mouseOver | css=.flex:nth-child(1) > .flex > .flex > .flex > .flex > .h-9:nth-child(2) > .relative | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(1) > .flex > .flex > .flex > .flex > .h-9:nth-child(2) > .relative")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseOut | css=.flex:nth-child(1) > .flex > .flex > .flex > .flex > .h-9:nth-child(2) > .relative | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 6 | click | css=.w-full:nth-child(6) .hidden:nth-child(1) > .flex:nth-child(4) .rounded-lg | 
    self.driver.find_element(By.CSS_SELECTOR, ".w-full:nth-child(6) .hidden:nth-child(1) > .flex:nth-child(4) .rounded-lg").click()
    # 7 | click | css=.pb-4:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".pb-4:nth-child(2)").click()
    # 8 | click | css=.\!text-xl | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\!text-xl").click()
    # 9 | type | css=.\!text-xl | 5 USD
    self.driver.find_element(By.CSS_SELECTOR, ".\\!text-xl").send_keys("5 USD")
    # 10 | click | css=.border-labs\/20 > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".border-labs\\/20 > span").click()
    # 11 | mouseOver | css=.border-labs\/20 > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".border-labs\\/20 > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | mouseOut | css=.border-labs\/20 > .flex | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
